from .. import lib

HELP_CUSTOMID_PAGE_ID_MAX_LENGTH = 2
HELP_CUSTOMID_ACCESS_ID_MAX_LENGTH = 2
HELP_CUSTOMID_ARGS_SEPARATOR = "#"
HELP_MAX_PAGE = lib.ids.maxIndex(HELP_CUSTOMID_PAGE_ID_MAX_LENGTH, exclusions=[HELP_CUSTOMID_ARGS_SEPARATOR])