# GitHub's default python testing workflow.
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --statistics
    
    - name: Run pyright
      uses: jakebailey/pyright-action@v1.3.0
#       with:
#         # Version of pyright to run. If not specified, the latest version will be used.
#         version: # optional
#         # Directory to run pyright in. If not specified, the repo root will be used.
#         working-directory: # optional
#         # Analyze for a specific platform (Darwin, Linux, Windows).
#         python-platform: # optional
#         # Analyze for a specific version (3.3, 3.4, etc.).
#         python-version: # optional
#         # Use typeshed type stubs at this location.
#         typeshed-path: # optional
#         # Directory that contains virtual environments.
#         venv-path: # optional
#         # Use the configuration file at this location.
#         project: # optional
#         # Use library code to infer types when stubs are missing.
#         lib: # optional, default is false
#         # Use exit code of 1 if warnings are reported.
#         warnings: # optional, default is false
#         # Package name to run the type verifier on; must be an *installed* library. Any score under 100% will fail the build.
#         verify-types: # optional
#         # Extra arguments; can be used to specify specific files to check.
#         extra-args: # optional
#         # Disable issue/commit comments
#         no-comments: # optional, default is false
